// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
// Regenerate with `GEN_TYPES=1 npm run db:test` (or `supabase gen types typescript`).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "12" }
  public: {
    Tables: {
      ai_insights: {
        Row: {
          id: string
          athlete_id: string
          insight_type: Database["public"]["Enums"]["ai_insight_type"]
          audience: Database["public"]["Enums"]["ai_audience"]
          status: Database["public"]["Enums"]["ai_insight_status"]
          title: string | null
          content: string | null
          source_refs: Json
          model: string | null
          prompt_version: string | null
          disclaimer: string
          requested_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          insight_type: Database["public"]["Enums"]["ai_insight_type"]
          audience?: Database["public"]["Enums"]["ai_audience"]
          status?: Database["public"]["Enums"]["ai_insight_status"]
          title?: string | null
          content?: string | null
          source_refs?: Json
          model?: string | null
          prompt_version?: string | null
          disclaimer?: string
          requested_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          insight_type?: Database["public"]["Enums"]["ai_insight_type"]
          audience?: Database["public"]["Enums"]["ai_audience"]
          status?: Database["public"]["Enums"]["ai_insight_status"]
          title?: string | null
          content?: string | null
          source_refs?: Json
          model?: string | null
          prompt_version?: string | null
          disclaimer?: string
          requested_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_insights_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_insights_requested_by_fkey"
            columns: ["requested_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      athletes: {
        Row: {
          id: string
          profile_id: string
          sport: string | null
          position: string | null
          team_name: string | null
          date_of_birth: string | null
          dominant_side: Database["public"]["Enums"]["body_side"] | null
          recovery_score_config: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          sport?: string | null
          position?: string | null
          team_name?: string | null
          date_of_birth?: string | null
          dominant_side?: Database["public"]["Enums"]["body_side"] | null
          recovery_score_config?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string
          sport?: string | null
          position?: string | null
          team_name?: string | null
          date_of_birth?: string | null
          dominant_side?: Database["public"]["Enums"]["body_side"] | null
          recovery_score_config?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "athletes_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          id: number
          table_name: string
          row_id: string | null
          athlete_id: string | null
          action: string
          actor_id: string | null
          old_data: Json | null
          new_data: Json | null
          created_at: string
        }
        Insert: {
          table_name: string
          row_id?: string | null
          athlete_id?: string | null
          action: string
          actor_id?: string | null
          old_data?: Json | null
          new_data?: Json | null
          created_at?: string
        }
        Update: {
          table_name?: string
          row_id?: string | null
          athlete_id?: string | null
          action?: string
          actor_id?: string | null
          old_data?: Json | null
          new_data?: Json | null
          created_at?: string
        }
        Relationships: [

        ]
      }
      daily_checkins: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string | null
          checkin_date: string
          pain: number
          swelling: number
          stiffness: number
          energy: number
          sleep: number
          mood: number
          confidence: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id?: string | null
          checkin_date?: string
          pain: number
          swelling: number
          stiffness: number
          energy: number
          sleep: number
          mood: number
          confidence: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string | null
          checkin_date?: string
          pain?: number
          swelling?: number
          stiffness?: number
          energy?: number
          sleep?: number
          mood?: number
          confidence?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_checkins_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "daily_checkins_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "daily_checkins_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
        ]
      }
      diagnoses: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string
          diagnosis: string
          grade: string | null
          diagnosed_on: string | null
          diagnosed_by: string | null
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id: string
          diagnosis: string
          grade?: string | null
          diagnosed_on?: string | null
          diagnosed_by?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string
          diagnosis?: string
          grade?: string | null
          diagnosed_on?: string | null
          diagnosed_by?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "diagnoses_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diagnoses_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "diagnoses_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "diagnoses_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
        ]
      }
      event_media: {
        Row: {
          id: string
          athlete_id: string
          injury_event_id: string | null
          milestone_id: string | null
          media_type: Database["public"]["Enums"]["media_type"]
          storage_path: string
          mime_type: string | null
          duration_seconds: number | null
          size_bytes: number | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_event_id?: string | null
          milestone_id?: string | null
          media_type: Database["public"]["Enums"]["media_type"]
          storage_path: string
          mime_type?: string | null
          duration_seconds?: number | null
          size_bytes?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_event_id?: string | null
          milestone_id?: string | null
          media_type?: Database["public"]["Enums"]["media_type"]
          storage_path?: string
          mime_type?: string | null
          duration_seconds?: number | null
          size_bytes?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "event_media_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_media_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_media_injury_event_id_athlete_id_fkey"
            columns: ["injury_event_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injury_events"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "event_media_injury_event_id_fkey"
            columns: ["injury_event_id"]
            isOneToOne: false
            referencedRelation: "injury_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "event_media_milestone_id_athlete_id_fkey"
            columns: ["milestone_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "milestones"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "event_media_milestone_id_fkey"
            columns: ["milestone_id"]
            isOneToOne: false
            referencedRelation: "milestones"
            referencedColumns: ["id"]
          },
        ]
      }
      exercise_logs: {
        Row: {
          id: string
          athlete_id: string
          exercise_id: string
          performed_on: string
          status: Database["public"]["Enums"]["exercise_log_status"]
          sets_done: number | null
          reps_done: number | null
          pain: number | null
          difficulty: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          exercise_id: string
          performed_on?: string
          status: Database["public"]["Enums"]["exercise_log_status"]
          sets_done?: number | null
          reps_done?: number | null
          pain?: number | null
          difficulty?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          exercise_id?: string
          performed_on?: string
          status?: Database["public"]["Enums"]["exercise_log_status"]
          sets_done?: number | null
          reps_done?: number | null
          pain?: number | null
          difficulty?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "exercise_logs_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "exercise_logs_exercise_id_athlete_id_fkey"
            columns: ["exercise_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "rehab_exercises"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "exercise_logs_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "rehab_exercises"
            referencedColumns: ["id"]
          },
        ]
      }
      injuries: {
        Row: {
          id: string
          athlete_id: string
          title: string
          body_region: string | null
          side: Database["public"]["Enums"]["body_side"] | null
          mechanism: string | null
          injured_on: string
          status: Database["public"]["Enums"]["injury_status"]
          is_primary: boolean
          availability_status: Database["public"]["Enums"]["availability_status"]
          return_to_training_status: Database["public"]["Enums"]["return_to_training_status"]
          expected_return_on: string | null
          next_review_on: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          title: string
          body_region?: string | null
          side?: Database["public"]["Enums"]["body_side"] | null
          mechanism?: string | null
          injured_on: string
          status?: Database["public"]["Enums"]["injury_status"]
          is_primary?: boolean
          availability_status?: Database["public"]["Enums"]["availability_status"]
          return_to_training_status?: Database["public"]["Enums"]["return_to_training_status"]
          expected_return_on?: string | null
          next_review_on?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          title?: string
          body_region?: string | null
          side?: Database["public"]["Enums"]["body_side"] | null
          mechanism?: string | null
          injured_on?: string
          status?: Database["public"]["Enums"]["injury_status"]
          is_primary?: boolean
          availability_status?: Database["public"]["Enums"]["availability_status"]
          return_to_training_status?: Database["public"]["Enums"]["return_to_training_status"]
          expected_return_on?: string | null
          next_review_on?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "injuries_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: true
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "injuries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      injury_events: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string | null
          event_type: Database["public"]["Enums"]["timeline_event_type"]
          title: string
          description: string | null
          occurred_on: string
          audience: Database["public"]["Enums"]["event_audience"]
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id?: string | null
          event_type: Database["public"]["Enums"]["timeline_event_type"]
          title: string
          description?: string | null
          occurred_on: string
          audience?: Database["public"]["Enums"]["event_audience"]
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string | null
          event_type?: Database["public"]["Enums"]["timeline_event_type"]
          title?: string
          description?: string | null
          occurred_on?: string
          audience?: Database["public"]["Enums"]["event_audience"]
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "injury_events_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "injury_events_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "injury_events_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "injury_events_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
        ]
      }
      integration_connections: {
        Row: {
          id: string
          athlete_id: string
          provider: string
          status: string
          scopes: string[]
          last_synced_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          provider: string
          status?: string
          scopes?: string[]
          last_synced_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          provider?: string
          status?: string
          scopes?: string[]
          last_synced_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "integration_connections_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
        ]
      }
      journal_entries: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string | null
          milestone_id: string | null
          entry_date: string
          title: string | null
          body: string | null
          mood: number | null
          visibility: Database["public"]["Enums"]["journal_visibility"]
          shared_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id?: string | null
          milestone_id?: string | null
          entry_date?: string
          title?: string | null
          body?: string | null
          mood?: number | null
          visibility?: Database["public"]["Enums"]["journal_visibility"]
          shared_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string | null
          milestone_id?: string | null
          entry_date?: string
          title?: string | null
          body?: string | null
          mood?: number | null
          visibility?: Database["public"]["Enums"]["journal_visibility"]
          shared_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "journal_entries_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "journal_entries_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "journal_entries_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "journal_entries_milestone_id_athlete_id_fkey"
            columns: ["milestone_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "milestones"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "journal_entries_milestone_id_fkey"
            columns: ["milestone_id"]
            isOneToOne: false
            referencedRelation: "milestones"
            referencedColumns: ["id"]
          },
        ]
      }
      journal_media: {
        Row: {
          id: string
          athlete_id: string
          journal_entry_id: string
          media_type: Database["public"]["Enums"]["media_type"]
          storage_path: string
          mime_type: string | null
          duration_seconds: number | null
          size_bytes: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          journal_entry_id: string
          media_type: Database["public"]["Enums"]["media_type"]
          storage_path: string
          mime_type?: string | null
          duration_seconds?: number | null
          size_bytes?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          journal_entry_id?: string
          media_type?: Database["public"]["Enums"]["media_type"]
          storage_path?: string
          mime_type?: string | null
          duration_seconds?: number | null
          size_bytes?: number | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "journal_media_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "journal_media_journal_entry_id_athlete_id_fkey"
            columns: ["journal_entry_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "journal_entries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "journal_media_journal_entry_id_fkey"
            columns: ["journal_entry_id"]
            isOneToOne: false
            referencedRelation: "journal_entries"
            referencedColumns: ["id"]
          },
        ]
      }
      medical_documents: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string | null
          title: string
          document_type: Database["public"]["Enums"]["document_type"]
          document_date: string | null
          storage_path: string
          mime_type: string | null
          size_bytes: number | null
          uploaded_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id?: string | null
          title: string
          document_type?: Database["public"]["Enums"]["document_type"]
          document_date?: string | null
          storage_path: string
          mime_type?: string | null
          size_bytes?: number | null
          uploaded_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string | null
          title?: string
          document_type?: Database["public"]["Enums"]["document_type"]
          document_date?: string | null
          storage_path?: string
          mime_type?: string | null
          size_bytes?: number | null
          uploaded_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "medical_documents_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "medical_documents_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "medical_documents_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "medical_documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      milestones: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string | null
          milestone_type: Database["public"]["Enums"]["milestone_type"]
          title: string
          status: Database["public"]["Enums"]["milestone_status"]
          target_on: string | null
          achieved_on: string | null
          notes: string | null
          sort_order: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id?: string | null
          milestone_type?: Database["public"]["Enums"]["milestone_type"]
          title: string
          status?: Database["public"]["Enums"]["milestone_status"]
          target_on?: string | null
          achieved_on?: string | null
          notes?: string | null
          sort_order?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string | null
          milestone_type?: Database["public"]["Enums"]["milestone_type"]
          title?: string
          status?: Database["public"]["Enums"]["milestone_status"]
          target_on?: string | null
          achieved_on?: string | null
          notes?: string | null
          sort_order?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "milestones_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestones_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestones_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "milestones_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          id: string
          recipient_id: string
          athlete_id: string | null
          type: Database["public"]["Enums"]["notification_type"]
          title: string
          body: string | null
          data: Json
          dedupe_key: string | null
          actor_id: string | null
          read_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          recipient_id: string
          athlete_id?: string | null
          type: Database["public"]["Enums"]["notification_type"]
          title: string
          body?: string | null
          data?: Json
          dedupe_key?: string | null
          actor_id?: string | null
          read_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          recipient_id?: string
          athlete_id?: string | null
          type?: Database["public"]["Enums"]["notification_type"]
          title?: string
          body?: string | null
          data?: Json
          dedupe_key?: string | null
          actor_id?: string | null
          read_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organisation_members: {
        Row: {
          id: string
          organisation_id: string
          profile_id: string
          role: Database["public"]["Enums"]["org_member_role"]
          status: Database["public"]["Enums"]["membership_status"]
          invited_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organisation_id: string
          profile_id: string
          role: Database["public"]["Enums"]["org_member_role"]
          status?: Database["public"]["Enums"]["membership_status"]
          invited_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organisation_id?: string
          profile_id?: string
          role?: Database["public"]["Enums"]["org_member_role"]
          status?: Database["public"]["Enums"]["membership_status"]
          invited_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "organisation_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organisation_members_organisation_id_fkey"
            columns: ["organisation_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organisation_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organisations: {
        Row: {
          id: string
          name: string
          slug: string | null
          kind: Database["public"]["Enums"]["org_kind"]
          logo_url: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug?: string | null
          kind?: Database["public"]["Enums"]["org_kind"]
          logo_url?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string | null
          kind?: Database["public"]["Enums"]["org_kind"]
          logo_url?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "organisations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      permissions: {
        Row: {
          id: string
          team_member_id: string
          athlete_id: string
          scope: Database["public"]["Enums"]["permission_scope"]
          granted_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          team_member_id: string
          athlete_id: string
          scope: Database["public"]["Enums"]["permission_scope"]
          granted_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          team_member_id?: string
          athlete_id?: string
          scope?: Database["public"]["Enums"]["permission_scope"]
          granted_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "permissions_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "permissions_granted_by_fkey"
            columns: ["granted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "permissions_team_member_id_athlete_id_fkey"
            columns: ["team_member_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "team_members"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "permissions_team_member_id_fkey"
            columns: ["team_member_id"]
            isOneToOne: false
            referencedRelation: "team_members"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_features: {
        Row: {
          plan: Database["public"]["Enums"]["subscription_plan"]
          feature: string
          limit_value: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          plan: Database["public"]["Enums"]["subscription_plan"]
          feature: string
          limit_value?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          plan?: Database["public"]["Enums"]["subscription_plan"]
          feature?: string
          limit_value?: number | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [

        ]
      }
      professionals: {
        Row: {
          id: string
          profile_id: string
          professional_role: Database["public"]["Enums"]["professional_role"]
          title: string | null
          registration_number: string | null
          bio: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          professional_role: Database["public"]["Enums"]["professional_role"]
          title?: string | null
          registration_number?: string | null
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string
          professional_role?: Database["public"]["Enums"]["professional_role"]
          title?: string | null
          registration_number?: string | null
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "professionals_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          full_name: string
          avatar_url: string | null
          primary_role: Database["public"]["Enums"]["app_role"] | null
          timezone: string
          notification_preferences: Json
          onboarded_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string
          avatar_url?: string | null
          primary_role?: Database["public"]["Enums"]["app_role"] | null
          timezone?: string
          notification_preferences?: Json
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          avatar_url?: string | null
          primary_role?: Database["public"]["Enums"]["app_role"] | null
          timezone?: string
          notification_preferences?: Json
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [

        ]
      }
      recovery_metrics: {
        Row: {
          id: string
          athlete_id: string
          metric_key: string
          value: number
          unit: string | null
          recorded_at: string
          source: Database["public"]["Enums"]["data_source"]
          provider: string | null
          external_id: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          metric_key: string
          value: number
          unit?: string | null
          recorded_at: string
          source?: Database["public"]["Enums"]["data_source"]
          provider?: string | null
          external_id?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          metric_key?: string
          value?: number
          unit?: string | null
          recorded_at?: string
          source?: Database["public"]["Enums"]["data_source"]
          provider?: string | null
          external_id?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "recovery_metrics_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
        ]
      }
      recovery_scores: {
        Row: {
          id: string
          athlete_id: string
          checkin_id: string | null
          score_date: string
          score: number
          components: Json
          algorithm_version: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          checkin_id?: string | null
          score_date: string
          score: number
          components?: Json
          algorithm_version: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          checkin_id?: string | null
          score_date?: string
          score?: number
          components?: Json
          algorithm_version?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "recovery_scores_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recovery_scores_checkin_id_athlete_id_fkey"
            columns: ["checkin_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "daily_checkins"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "recovery_scores_checkin_id_fkey"
            columns: ["checkin_id"]
            isOneToOne: false
            referencedRelation: "daily_checkins"
            referencedColumns: ["id"]
          },
        ]
      }
      rehab_exercises: {
        Row: {
          id: string
          athlete_id: string
          programme_id: string
          phase_id: string | null
          name: string
          sets: number | null
          reps: number | null
          duration_seconds: number | null
          tempo: string | null
          load: string | null
          instructions: string | null
          video_url: string | null
          notes: string | null
          schedule_days: number[]
          sort_order: number
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          programme_id: string
          phase_id?: string | null
          name: string
          sets?: number | null
          reps?: number | null
          duration_seconds?: number | null
          tempo?: string | null
          load?: string | null
          instructions?: string | null
          video_url?: string | null
          notes?: string | null
          schedule_days?: number[]
          sort_order?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          programme_id?: string
          phase_id?: string | null
          name?: string
          sets?: number | null
          reps?: number | null
          duration_seconds?: number | null
          tempo?: string | null
          load?: string | null
          instructions?: string | null
          video_url?: string | null
          notes?: string | null
          schedule_days?: number[]
          sort_order?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "rehab_exercises_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rehab_exercises_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rehab_exercises_phase_id_athlete_id_fkey"
            columns: ["phase_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "rehab_phases"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "rehab_exercises_phase_id_fkey"
            columns: ["phase_id"]
            isOneToOne: false
            referencedRelation: "rehab_phases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rehab_exercises_programme_id_athlete_id_fkey"
            columns: ["programme_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "rehab_programmes"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "rehab_exercises_programme_id_fkey"
            columns: ["programme_id"]
            isOneToOne: false
            referencedRelation: "rehab_programmes"
            referencedColumns: ["id"]
          },
        ]
      }
      rehab_phases: {
        Row: {
          id: string
          athlete_id: string
          programme_id: string
          name: string
          goals: string | null
          sort_order: number
          status: Database["public"]["Enums"]["phase_status"]
          starts_on: string | null
          ends_on: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          programme_id: string
          name: string
          goals?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["phase_status"]
          starts_on?: string | null
          ends_on?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          programme_id?: string
          name?: string
          goals?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["phase_status"]
          starts_on?: string | null
          ends_on?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "rehab_phases_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rehab_phases_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rehab_phases_programme_id_athlete_id_fkey"
            columns: ["programme_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "rehab_programmes"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "rehab_phases_programme_id_fkey"
            columns: ["programme_id"]
            isOneToOne: true
            referencedRelation: "rehab_programmes"
            referencedColumns: ["id"]
          },
        ]
      }
      rehab_programmes: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string | null
          programme_type: Database["public"]["Enums"]["programme_type"]
          title: string
          description: string | null
          status: Database["public"]["Enums"]["programme_status"]
          starts_on: string | null
          ends_on: string | null
          protocol_key: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id?: string | null
          programme_type?: Database["public"]["Enums"]["programme_type"]
          title: string
          description?: string | null
          status?: Database["public"]["Enums"]["programme_status"]
          starts_on?: string | null
          ends_on?: string | null
          protocol_key?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string | null
          programme_type?: Database["public"]["Enums"]["programme_type"]
          title?: string
          description?: string | null
          status?: Database["public"]["Enums"]["programme_status"]
          starts_on?: string | null
          ends_on?: string | null
          protocol_key?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "rehab_programmes_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rehab_programmes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rehab_programmes_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "rehab_programmes_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
        ]
      }
      restrictions: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string | null
          activity: string
          label: string | null
          level: Database["public"]["Enums"]["restriction_level"]
          notes: string | null
          effective_from: string
          review_on: string | null
          set_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id?: string | null
          activity: string
          label?: string | null
          level: Database["public"]["Enums"]["restriction_level"]
          notes?: string | null
          effective_from?: string
          review_on?: string | null
          set_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string | null
          activity?: string
          label?: string | null
          level?: Database["public"]["Enums"]["restriction_level"]
          notes?: string | null
          effective_from?: string
          review_on?: string | null
          set_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "restrictions_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "restrictions_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "restrictions_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "restrictions_set_by_fkey"
            columns: ["set_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      role_default_permissions: {
        Row: {
          role: Database["public"]["Enums"]["professional_role"]
          scope: Database["public"]["Enums"]["permission_scope"]
          created_at: string
          updated_at: string
        }
        Insert: {
          role: Database["public"]["Enums"]["professional_role"]
          scope: Database["public"]["Enums"]["permission_scope"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          role?: Database["public"]["Enums"]["professional_role"]
          scope?: Database["public"]["Enums"]["permission_scope"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [

        ]
      }
      subscriptions: {
        Row: {
          id: string
          profile_id: string | null
          organisation_id: string | null
          plan: Database["public"]["Enums"]["subscription_plan"]
          status: Database["public"]["Enums"]["subscription_status"]
          seats: number | null
          current_period_end: string | null
          provider: string | null
          provider_customer_id: string | null
          provider_subscription_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id?: string | null
          organisation_id?: string | null
          plan: Database["public"]["Enums"]["subscription_plan"]
          status?: Database["public"]["Enums"]["subscription_status"]
          seats?: number | null
          current_period_end?: string | null
          provider?: string | null
          provider_customer_id?: string | null
          provider_subscription_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string | null
          organisation_id?: string | null
          plan?: Database["public"]["Enums"]["subscription_plan"]
          status?: Database["public"]["Enums"]["subscription_status"]
          seats?: number | null
          current_period_end?: string | null
          provider?: string | null
          provider_customer_id?: string | null
          provider_subscription_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_organisation_id_fkey"
            columns: ["organisation_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      surgeries: {
        Row: {
          id: string
          athlete_id: string
          injury_id: string
          procedure: string
          surgeon: string | null
          facility: string | null
          performed_on: string | null
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          injury_id: string
          procedure: string
          surgeon?: string | null
          facility?: string | null
          performed_on?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          injury_id?: string
          procedure?: string
          surgeon?: string | null
          facility?: string | null
          performed_on?: string | null
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "surgeries_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "surgeries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "surgeries_injury_id_athlete_id_fkey"
            columns: ["injury_id", "athlete_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id", "athlete_id"]
          },
          {
            foreignKeyName: "surgeries_injury_id_fkey"
            columns: ["injury_id"]
            isOneToOne: false
            referencedRelation: "injuries"
            referencedColumns: ["id"]
          },
        ]
      }
      team_members: {
        Row: {
          id: string
          athlete_id: string
          professional_id: string | null
          invited_email: string
          role: Database["public"]["Enums"]["professional_role"]
          status: Database["public"]["Enums"]["connection_status"]
          organisation_id: string | null
          invited_by: string | null
          accepted_at: string | null
          revoked_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          professional_id?: string | null
          invited_email: string
          role: Database["public"]["Enums"]["professional_role"]
          status?: Database["public"]["Enums"]["connection_status"]
          organisation_id?: string | null
          invited_by?: string | null
          accepted_at?: string | null
          revoked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          professional_id?: string | null
          invited_email?: string
          role?: Database["public"]["Enums"]["professional_role"]
          status?: Database["public"]["Enums"]["connection_status"]
          organisation_id?: string | null
          invited_by?: string | null
          accepted_at?: string | null
          revoked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_members_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_members_organisation_id_fkey"
            columns: ["organisation_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_members_professional_id_fkey"
            columns: ["professional_id"]
            isOneToOne: false
            referencedRelation: "professionals"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      accept_team_invite: { Args: { p_team_member_id: string }; Returns: Database["public"]["Tables"]["team_members"]["Row"] }
      can_access: { Args: { p_athlete_id: string; p_scope: Database["public"]["Enums"]["permission_scope"] }; Returns: boolean }
      can_read_event: { Args: { p_event_id: string }; Returns: boolean }
      can_read_programme: { Args: { p_programme_id: string }; Returns: boolean }
      can_read_shared_journal_entry: { Args: { p_entry_id: string }; Returns: boolean }
      can_view_profile: { Args: { p_profile_id: string }; Returns: boolean }
      can_write_programme: { Args: { p_programme_id: string }; Returns: boolean }
      complete_onboarding: { Args: { p_role: Database["public"]["Enums"]["app_role"]; p_full_name: string; p_details?: Json }; Returns: Database["public"]["Tables"]["profiles"]["Row"] }
      current_athlete_id: { Args: never; Returns: string }
      current_plan: { Args: never; Returns: Database["public"]["Enums"]["subscription_plan"] }
      current_professional_id: { Args: never; Returns: string }
      current_user_email: { Args: never; Returns: string }
      decline_team_invite: { Args: { p_team_member_id: string }; Returns: undefined }
      entitlement_limit: { Args: { p_feature: string }; Returns: number }
      get_athlete_status_board: { Args: never; Returns: { athlete_id: string | null; full_name: string | null; avatar_url: string | null; sport: string | null; team_name: string | null; availability_status: Database["public"]["Enums"]["availability_status"] | null; return_to_training_status: Database["public"]["Enums"]["return_to_training_status"] | null; current_phase: string | null; next_review_on: string | null; expected_return_on: string | null; restrictions: Json | null; next_milestone: Json | null; updated_at: string | null }[] }
      get_my_entitlements: { Args: never; Returns: Json }
      has_entitlement: { Args: { p_feature: string }; Returns: boolean }
      has_scope: { Args: { p_athlete_id: string; p_scope: Database["public"]["Enums"]["permission_scope"] }; Returns: boolean }
      invite_team_member: { Args: { p_email: string; p_role: Database["public"]["Enums"]["professional_role"]; p_scopes?: Database["public"]["Enums"]["permission_scope"][] }; Returns: Database["public"]["Tables"]["team_members"]["Row"] }
      is_athlete_owner: { Args: { p_athlete_id: string }; Returns: boolean }
      is_connected_professional: { Args: { p_athlete_id: string }; Returns: boolean }
      is_org_admin: { Args: { p_org_id: string }; Returns: boolean }
      is_org_member: { Args: { p_org_id: string }; Returns: boolean }
      mark_all_notifications_read: { Args: never; Returns: undefined }
      revoke_team_member: { Args: { p_team_member_id: string }; Returns: undefined }
      safe_uuid: { Args: { p_text: string }; Returns: string }
      set_team_member_permissions: { Args: { p_team_member_id: string; p_scopes: Database["public"]["Enums"]["permission_scope"][] }; Returns: undefined }
    }
    Enums: {
      ai_audience: "athlete" | "professional"
      ai_insight_status: "pending" | "ready" | "failed" | "dismissed"
      ai_insight_type: "copilot_message" | "recovery_trend_summary" | "journal_summary" | "document_summary" | "milestone_suggestion" | "athlete_progress_summary" | "professional_progress_summary"
      app_role: "athlete" | "physio" | "sc_coach" | "team_coach" | "doctor" | "support_staff" | "org_admin"
      availability_status: "available" | "modified" | "unavailable"
      body_side: "left" | "right" | "bilateral" | "not_applicable"
      connection_status: "pending" | "active" | "declined" | "revoked"
      data_source: "manual" | "checkin" | "wearable" | "gps" | "camera" | "import"
      document_type: "imaging_report" | "surgical_report" | "clinical_letter" | "referral" | "scan_image" | "other"
      event_audience: "private" | "team" | "clinical"
      exercise_log_status: "completed" | "partial" | "skipped"
      injury_status: "active" | "recovered" | "archived"
      journal_visibility: "private" | "shared"
      media_type: "photo" | "video" | "voice" | "document"
      membership_status: "invited" | "active" | "removed"
      milestone_status: "planned" | "achieved" | "deferred"
      milestone_type: "pain_free_walk" | "full_rom" | "first_bike" | "first_gym" | "first_run" | "first_sprint" | "first_change_of_direction" | "first_team_training" | "return_to_contact" | "first_match" | "custom"
      notification_type: "rehab_programme_created" | "exercise_assigned" | "rehab_completed" | "restriction_changed" | "milestone_completed" | "professional_comment" | "connection_created" | "recovery_trend_alert"
      org_kind: "club" | "clinic" | "team" | "academy" | "other"
      org_member_role: "admin" | "professional" | "athlete"
      permission_scope: "availability.read" | "injury.read" | "restrictions.read" | "restrictions.write" | "rehab.read" | "rehab.write" | "training.write" | "checkins.read" | "metrics.read" | "milestones.read" | "milestones.write" | "timeline.read" | "timeline.write" | "medical.read" | "medical.write" | "documents.read" | "documents.write" | "journal.shared.read" | "insights.read"
      phase_status: "upcoming" | "current" | "completed"
      professional_role: "physio" | "sc_coach" | "team_coach" | "doctor" | "support_staff"
      programme_status: "draft" | "active" | "completed" | "archived"
      programme_type: "rehab" | "conditioning"
      restriction_level: "green" | "yellow" | "red"
      return_to_training_status: "rehab_only" | "individual_training" | "modified_team_training" | "full_team_training" | "match_available"
      subscription_plan: "free" | "premium_athlete" | "pro_clinic"
      subscription_status: "trialing" | "active" | "past_due" | "canceled" | "incomplete"
      timeline_event_type: "injury" | "diagnosis" | "imaging" | "surgery" | "specialist_appointment" | "physiotherapy" | "rehab_milestone" | "training_milestone" | "return_to_run" | "return_to_contact" | "return_to_play" | "note" | "other"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database["public"]
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]
export type Functions<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T]

export const Constants = {
  public: {
    Enums: {
      ai_audience: ["athlete", "professional"],
      ai_insight_status: ["pending", "ready", "failed", "dismissed"],
      ai_insight_type: ["copilot_message", "recovery_trend_summary", "journal_summary", "document_summary", "milestone_suggestion", "athlete_progress_summary", "professional_progress_summary"],
      app_role: ["athlete", "physio", "sc_coach", "team_coach", "doctor", "support_staff", "org_admin"],
      availability_status: ["available", "modified", "unavailable"],
      body_side: ["left", "right", "bilateral", "not_applicable"],
      connection_status: ["pending", "active", "declined", "revoked"],
      data_source: ["manual", "checkin", "wearable", "gps", "camera", "import"],
      document_type: ["imaging_report", "surgical_report", "clinical_letter", "referral", "scan_image", "other"],
      event_audience: ["private", "team", "clinical"],
      exercise_log_status: ["completed", "partial", "skipped"],
      injury_status: ["active", "recovered", "archived"],
      journal_visibility: ["private", "shared"],
      media_type: ["photo", "video", "voice", "document"],
      membership_status: ["invited", "active", "removed"],
      milestone_status: ["planned", "achieved", "deferred"],
      milestone_type: ["pain_free_walk", "full_rom", "first_bike", "first_gym", "first_run", "first_sprint", "first_change_of_direction", "first_team_training", "return_to_contact", "first_match", "custom"],
      notification_type: ["rehab_programme_created", "exercise_assigned", "rehab_completed", "restriction_changed", "milestone_completed", "professional_comment", "connection_created", "recovery_trend_alert"],
      org_kind: ["club", "clinic", "team", "academy", "other"],
      org_member_role: ["admin", "professional", "athlete"],
      permission_scope: ["availability.read", "injury.read", "restrictions.read", "restrictions.write", "rehab.read", "rehab.write", "training.write", "checkins.read", "metrics.read", "milestones.read", "milestones.write", "timeline.read", "timeline.write", "medical.read", "medical.write", "documents.read", "documents.write", "journal.shared.read", "insights.read"],
      phase_status: ["upcoming", "current", "completed"],
      professional_role: ["physio", "sc_coach", "team_coach", "doctor", "support_staff"],
      programme_status: ["draft", "active", "completed", "archived"],
      programme_type: ["rehab", "conditioning"],
      restriction_level: ["green", "yellow", "red"],
      return_to_training_status: ["rehab_only", "individual_training", "modified_team_training", "full_team_training", "match_available"],
      subscription_plan: ["free", "premium_athlete", "pro_clinic"],
      subscription_status: ["trialing", "active", "past_due", "canceled", "incomplete"],
      timeline_event_type: ["injury", "diagnosis", "imaging", "surgery", "specialist_appointment", "physiotherapy", "rehab_milestone", "training_milestone", "return_to_run", "return_to_contact", "return_to_play", "note", "other"],
    },
  },
} as const
