#!/usr/bin/env bash
# Combines every migration into supabase/setup.sql so a fresh project can be
# set up with one paste into the Supabase SQL Editor.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/setup.sql"
{
  echo "-- ============================================================================="
  echo "-- Comeback HQ — complete database setup (GENERATED by scripts/bundle-sql.sh)"
  echo "-- Paste into Supabase → SQL Editor → Run, on a NEW project, once."
  echo "-- If anything fails, the whole script is rolled back — nothing is half-applied."
  echo "-- ============================================================================="
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo; echo "-- >>> $(basename "$f")"; echo
    cat "$f"
  done
  echo
  echo "select 'Comeback HQ database ready' as status;"
} > "$OUT"
echo "wrote $OUT"
